player_lists = [
"Alisson Becker",
"David De Gea",
"Ederson Moraes",
"Jan Oblak",
"Marc-Andre ter Stegen",
"Jordi Alba",
"Trent Alexander-Arnold",
"Dani Alves",
"Joao Cancelo",
"Daniel Carvajal",
"Giorgio Chiellini",
"Matthijs de Ligt",
"Diego Godin",
"Joshua Kimmich",
"Kalidou Koulibaly",
"Aymeric Laporte",
"Marcelo Vieira da Silva Júnior",
"Gerard Pique",
"Sergio Ramos",
"Andrew Robertson",
"Alex Sandro",
"Thiago Silva",
"Virgil van Dijk",
"Raphael Varane",
# "Kyle Walker",
"Sergio Busquets",
# "Casemiro",
"Kevin de Bruyne",
"Frenkie de Jong",
"Christian Eriksen",
"Eden Hazard",
"N'Golo Kante",
"Toni Kroos",
"Arthur Melo",
"Luka Modric",
# "Paul Pogba",
"Ivan Rakitic",
# "Bernardo Silva",
"Dusan Tadic",
# "Arturo Erasmo Vidal Pardo",
"Sergio Aguero",
# "Karim Benzema",
"Cristiano Ronaldo",
"Roberto Firmino",
"Antoine Griezmann",
"Son Heungmin",
"Harry Kane",
"Robert Lewandowski",
# "Sadio Mane",
# "Kylian Mbappe",
"Lionel Messi",
# "Neymar",
# "Mohamed Salah",
"Raheem Sterling",
"Luis Suarez",
]

def return_player_lists():
  return player_lists